### ISSUE TITLE
java.lang.NoSuchFieldError: Class ...JavaSystemSetting does not have member field '...JavaSystemSetting USER_REGION'

### ISSUE THREAD

**Issue by victzero** [amazon-contributing/aurora-dsql-benchbase-benchmarking#60]
**OS:** 
Amazon Linux 2023

**Java SDK:**
openjdk 21.0.5 2024-10-15 LTS
OpenJDK Runtime Environment Corretto-21.0.5.11.1 (build 21.0.5+11-LTS)
OpenJDK 64-Bit Server VM Corretto-21.0.5.11.1 (build 21.0.5+11-LTS, mixed mode, sharing)

**Error**:
java.lang.NoSuchFieldError: Class software.amazon.awssdk.utils.JavaSystemSetting does not have member field 'software.amazon.awssdk.utils.JavaSystemSetting USER_REGION'
	at software.amazon.awssdk.core.util.SdkUserAgent.getUserAgent(SdkUserAgent.java:101)
	at software.amazon.awssdk.core.util.SdkUserAgent.initializeUserAgent(SdkUserAgent.java:95)
	at software.amazon.awssdk.core.util.SdkUserAgent.<init>(SdkUserAgent.java:65)
	at software.amazon.awssdk.core.util.SdkUserAgent.create(SdkUserAgent.java:72)
	at software.amazon.awssdk.regions.internal.util.InstanceProviderTokenEndpointProvider.headers(InstanceProviderTokenEndpointProvider.java:46)
	at software.amazon.awssdk.regions.util.HttpResourcesUtils.readResource(HttpResourcesUtils.java:113)
	at software.amazon.awssdk.regions.internal.util.EC2MetadataUtils.getToken(EC2MetadataUtils.java:436)
	at software.amazon.awssdk.regions.internal.util.EC2MetadataUtils.getItems(EC2MetadataUtils.java:398)
	at software.amazon.awssdk.regions.internal.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:362)
	at software.amazon.awssdk.regions.internal.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:358)
	at software.amazon.awssdk.regions.internal.util.EC2MetadataUtils.getEC2InstanceRegion(EC2MetadataUtils.java:242)
	at software.amazon.awssdk.regions.providers.InstanceProfileRegionProvider.tryDetectRegion(InstanceProfileRegionProvider.java:72)
	at software.amazon.awssdk.regions.providers.InstanceProfileRegionProvider.getRegion(InstanceProfileRegionProvider.java:56)
	at software.amazon.awssdk.regions.providers.AwsRegionProviderChain.getRegion(AwsRegionProviderChain.java:51)
	at com.oltpbenchmark.util.IAMUtil.generateAuroraDsqlPasswordToken(IAMUtil.java:32)
	at com.oltpbenchmark.util.IAMUtil.generateAuroraDsqlPasswordToken(IAMUtil.java:18)
	at com.oltpbenchmark.api.BenchmarkModule.makeConnection(BenchmarkModule.java:98)
	at com.oltpbenchmark.util.ConnectionUtil.makeConnectionWithRetry(ConnectionUtil.java:21)
	at com.oltpbenchmark.api.BenchmarkModule.createDatabase(BenchmarkModule.java:229)
	at com.oltpbenchmark.DBWorkload.runCreator(DBWorkload.java:767)
	at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:487)

**Comment by victzero** [comment]
Fixed by replace the aws SDK version in pom.xml from line 379 to 399.
Use version 2.29.27 for all awssdk dependencies shown as below:

```
        <!-- For Aurora Dsql Token Generation -->
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>dsql</artifactId>
            <version>2.29.27</version>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>regions</artifactId>
            <version>2.29.27</version>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>sdk-core</artifactId>
            <version>2.29.27</version>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>auth</artifactId>
            <version>2.29.27</version>
        </dependency>

```
